/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package semonster2;

import org.junit.Test;
import static org.junit.Assert.*;

import java.io.ByteArrayInputStream;

public class AppTest {
    @Test public void appHasAGreeting() {
        App classUnderTest = new App();
        assertEquals("こんにちは SEMonster", classUnderTest.getGreeting());
    }

  @Test
  public void testGetPlayerName() {
    var userName = "test_user";
    var testIn = new ByteArrayInputStream("test_user".getBytes());
    System.setIn(testIn);

    assertEquals(userName, App.getPlayerName(App.stdin));
  }

  @Test
  public void testGetRandomList() {
    var result = App.getRandomList(1);
    assertNotNull(result);
    assertEquals(1, result.size());
  }
}
