/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package semonster2;

public class App {
    public String getGreeting() {
        return "こんにちは SEMonster";
  static String getPlayerName(Scanner scanner) {
    return scanner.next();
  }
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
